import type { LocationDef } from '../types';

// Ten locations, rent-laddered like the original's Suburbs → Hexa-Stad,
// flavored from the real stores' documented vibes.
export const LOCATIONS: LocationDef[] = [
  {
    id: 'driveway',
    name: 'Your Driveway (Silver Lake)',
    rent: 0,
    blurb:
      'A folding table on your own driveway. Light foot traffic, but the rent is free and your roommates are supportive.',
    baseTraffic: 14,
    wealth: 18,
    basePopularity: 0.7,
    baseSatisfaction: 0.8,
    touristy: 0.0,
    industry: 0.1,
    sceneColors: { sky: '#cfe3ea', ground: '#7cb85c', accent: '#4a9e46' },
  },
  {
    id: 'silverlake',
    name: 'Silver Lake',
    rent: 40,
    blurb:
      'Eastside creatives and music producers. They will ask if the sea moss is ethically sourced.',
    baseTraffic: 25,
    wealth: 20,
    basePopularity: 0.6,
    baseSatisfaction: 0.5,
    touristy: 0.15,
    industry: 0.25,
    sceneColors: { sky: '#cfe3ea', ground: '#74b054', accent: '#43a047' },
  },
  {
    id: 'culver',
    name: 'Culver City',
    rent: 120,
    blurb:
      'Tech and studio professionals on a tight lunch break. They order fast and expense it.',
    baseTraffic: 35,
    wealth: 21,
    basePopularity: 0.5,
    baseSatisfaction: 0.4,
    touristy: 0.1,
    industry: 0.8,
    sceneColors: { sky: '#d5e6ee', ground: '#a4adb5', accent: '#3f6fd9' },
  },
  {
    id: 'studio',
    name: 'Studio City',
    rent: 120,
    blurb:
      'Industry people of the Valley. Everyone here is attached to a project.',
    baseTraffic: 35,
    wealth: 22,
    basePopularity: 0.4,
    baseSatisfaction: 0.6,
    touristy: 0.1,
    industry: 0.85,
    sceneColors: { sky: '#e8e0cf', ground: '#c8a96e', accent: '#c78f3f' },
  },
  {
    id: 'venice',
    name: 'Venice (Abbot Kinney)',
    rent: 160,
    blurb:
      'Beach crowds and tourists off Abbot Kinney. Great on sunny days.',
    baseTraffic: 45,
    wealth: 23,
    basePopularity: 0.7,
    baseSatisfaction: 0.3,
    touristy: 0.8,
    industry: 0.1,
    sceneColors: { sky: '#bfe0ec', ground: '#e8cf8e', accent: '#2f9ea8' },
  },
  {
    id: 'santamonica',
    name: 'Santa Monica',
    rent: 200,
    blurb:
      'Content creators and promenade tourists. Every third customer is holding a ring light.',
    baseTraffic: 50,
    wealth: 24,
    basePopularity: 0.6,
    baseSatisfaction: 0.3,
    touristy: 0.85,
    industry: 0.1,
    sceneColors: { sky: '#bfe0ec', ground: '#e3ca88', accent: '#2f86c7' },
  },
  {
    id: 'calabasas',
    name: 'Calabasas',
    rent: 200,
    blurb:
      'Teenagers with a parent\'s credit card. Prices are not an obstacle here.',
    baseTraffic: 45,
    wealth: 26,
    basePopularity: 0.3,
    baseSatisfaction: 0.8,
    touristy: 0.05,
    industry: 0.3,
    sceneColors: { sky: '#e9ddc8', ground: '#84b660', accent: '#cf9c3f' },
  },
  {
    id: 'beverlygrove',
    name: 'Beverly Grove',
    rent: 400,
    blurb:
      'The original. Peak influencer density, legendary parking situation.',
    baseTraffic: 70,
    wealth: 27,
    basePopularity: 0.8,
    baseSatisfaction: 0.2,
    touristy: 0.5,
    industry: 0.4,
    sceneColors: { sky: '#d8e4ea', ground: '#b0b0a8', accent: '#7b5ec7' },
  },
  {
    id: 'beverlyhills',
    name: 'Beverly Hills',
    rent: 400,
    blurb:
      'Tourists and devoted regulars. Ground zero of the $19 strawberry.',
    baseTraffic: 70,
    wealth: 28,
    basePopularity: 0.6,
    baseSatisfaction: 0.4,
    touristy: 0.75,
    industry: 0.3,
    sceneColors: { sky: '#d8e4ea', ground: '#95bd6f', accent: '#c76f5a' },
  },
  {
    id: 'palisades',
    name: 'The Palisades',
    rent: 600,
    blurb:
      'Quiet money on quick produce runs. The most serene customers in Los Angeles.',
    baseTraffic: 90,
    wealth: 30,
    basePopularity: 0.2,
    baseSatisfaction: 0.9,
    touristy: 0.1,
    industry: 0.2,
    sceneColors: { sky: '#c8e2ee', ground: '#79b45c', accent: '#3f9e63' },
  },
];

export const LOCATION_BY_ID = Object.fromEntries(LOCATIONS.map((l) => [l.id, l]));
